# redis-hybrid.conf

# RDB 자동 저장은 끕니다 (AOF Rewrite 시 RDB가 생성되므로 중복 작업 방지)
save ""

# AOF 활성화 및 1초 주기로 디스크 동기화
appendonly yes
appendfsync everysec

# 하이브리드 모드 켜기 (Redis 5.0+ 기본값)
aof-use-rdb-preamble yes

dir /data