# redis-aof.conf

# RDB 자동 저장 끄기
save ""

# AOF 활성화
appendonly yes

# 파일 동기화 옵션: always(항상), everysec(1초마다 - 권장), no(OS에 위임)
appendfsync everysec

# AOF 파일명 및 경로 (Redis 7.0 이상부터는 폴더 형태로 관리됨)
appenddirname "appendonlydir"
appendfilename "appendonly.aof"
dir /data